version: '3.5'
services:
  dev:
    build:
      context: .
      args:
        - BUILD_ARG=acc
    image: docker-registry.secure.amsterdam.nl/ruimte/hior:${VERSION:-latest}  
    environment:
      - TZ=Europe/Amsterdam
    ipc: host
    ports:
      - "8000:8000"

  unittest:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=test
      - CI=true
      - TZ=Europe/Amsterdam
      - BUILD_ARG=acc
    command: npm run test
