FROM python:3.11-bookworm as app
MAINTAINER datapunt@amsterdam.nl

ENV PYTHONUNBUFFERED 1 \
    PIP_NO_CACHE_DIR=off

RUN  apt-get update \
 && apt-get dist-upgrade -y \
 && pip install --upgrade pip \
 && pip3 install pandas openpyxl azure-storage-blob \
 && useradd --user-group --system datapunt

USER datapunt