version: "3.5"
services:
  dev:
    build:
      context: .
    image: ${REGISTRY:-localhost:5001}/${REPOSITORY:-opdrachten/hior}:${VERSION:-latest}
    environment:
      - TZ=Europe/Amsterdam
      - REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING=${REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING}
    ipc: host
    ports:
      - "8080:8080"

  test:
    build:
      context: .
      target: builder
    environment:
      - CI=true
      - TZ=Europe/Amsterdam
    command: npm run test

  upgrade:
    build:
      context: .
      target: upgrade
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: ncu -u --doctor --target minor

  csv-update:
    build:
      dockerfile: Dockerfile-csv-update
    image: ${REGISTRY:-localhost:5001}/${REPOSITORY:-opdrachten/hior-csv-update}:${VERSION:-latest}
    environment:
      - AZURE_STORAGE_CONTAINER_NAME_CSV=foo
      - AZURE_STORAGE_CONTAINER=
      - XLSX_FILE=http://131f4363709c46b89a6ba5bc764b38b9.objectstore.eu/hior/HIOR%20Amsterdam.xlsx
    volumes:
      - ./import_hior.py:/app/import_hior.py
    command: python3 /app/import_hior.py
