version: '3.5'
services:
  web:
    build:
      context: .
      args:
        - BUILD_ARG=acc
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-opdrachten/hior}:${VERSION:-latest}
    environment:
      - TZ=Europe/Amsterdam
      - REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING=${REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING}
    ipc: host
    ports:
      - '3000:8080'

  unittest:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=test
      - CI=true
      - TZ=Europe/Amsterdam
      - BUILD_ARG=acc
    command: npm run test
