image:
  registry: myregistry.com
  repository: repository
  tag: 1.2.3

tenantId: tenant-id
keyVaultName: keyvault-name
keyVaultIdentity: keyvault-identity

nodepool: nodepool

persistentVolumeClaims:
  data:
    resources:
      requests:
        storage: 1Gi

jobs:
  migrate:
    annotations:
      helm.sh/hook: post-install,post-upgrade
    labels:
      component: migrate
    volumes:
      - name: tmp
        spec:
          emptyDir: {}
    containers:
      - name: main
        secrets:
          - vault
        volumes:
          - name: tmp
            mountPath: /tmp
        command:
          - python
          - manage.py
          - migrate

cronJobs:
  migrate:
    labels:
      component: import
    schedule: "0 * * * *"
    volumes:
      - name: tmp
        mountPath: /tmp
        spec:
          emptyDir: {}
    containers:
      - name: main
        volumes:
          - name: tmp
            mountPath: /tmp
        secrets:
          - vault
        command:
          - python
          - manage.py
          - import_api

deployments:
  app:
    securityContext:
      runAsUser: 2000
    labels:
      component: app
    autoscale:
      cpu: 70
      memory: 90
      min: 3
      max: 8
    resources:
      requests:
        cpu: 1
        memory: "512Mi"
      limits:
        cpu: 1
        memory: "512Mi"
    volumes:
      - name: data
        persistentVolumeClaim: data
      - name: tmp
        spec:
          emptyDir: {}
    containers:
      - name: main
        resources:
          limits:
            cpu: 4
        secrets:
          - simple
        volumes:
          - name: tmp
            mountPath: /tmp
      - name: foo
        image: 
          tag: "1.3.3.7"
        command:
          - sleep
        args:
          - "10"
        volumes:
          - name: data
            mountPath: /data
        secrets:
          - vault
        securityContext:
          privileged: true

secrets:
  simple:
    type: opaque
    secrets:
      foo: bar
      hello: world
  vault:
    type: keyvault
    secrets:
      - secret1
      - secret2
      - secret3
