image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  repository: opdrachten/hior
  tag: latest

labels:
  app: hior

network:
  allow-ingress:
    selector: app == 'hior'
    ingress:
      - action: Allow
    egress:
      - action: Allow

deployments:
  app:
    containers:
      - name: main
        volumes:
          - name: tmp
            mountPath: /tmp
        secrets:
          - vault
        ports:
          - port: 8080
            name: http
    volumes:
      - name: tmp
        spec:
          emptyDir: {}
    tempDirs:
      - /tmp

jobs:
  certificate-init:
    secrets:
      - certificate
    annotations:
      helm.sh/hook: post-install,post-upgrade
    containers:
      - name: main
        command:
          - sleep
        args:
          - "1"

services:
  app:
    ports:
      - name: http
        port: 80
        targetPort: 8080
    selector:
      app: hior

ingress:
  app:
    paths:
    - path: /
      service: app
      port: 80
    className: nginx
    tls: certificate

secrets:
  certificate:
    type: keyvault
    tls: hior
  vault:
    type: keyvault
    annotations:
      helm.sh/hook-weight: "-5"
    secrets:
      REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING: applicationinsights-connection-string