trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

parameters:
  - name: versionOverride
    displayName: "[OPTIONAL] Build/deploy version override"
    type: string
    default: ' '

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: hior
    ${{ if ne(parameters.versionOverride, ' ') }}:
      version: ${{ parameters.versionOverride }}
    build:
      producedImages:
      - opdrachten/hior
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-hior
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-ont-01-hior"
    test:
      pool: Opdrachten
      namespace: ns-ccc-opdr-tst-01-hior
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-tst-01-hior"
    acc:
      pool: Opdrachten
      namespace: ns-ccc-opdr-acc-01-hior
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-acc-01-hior"
      preSteps:
        - script: helm uninstall hior -n ns-ccc-opdr-acc-01-hior || true
    prod:
      pool: Opdrachten
      namespace: ns-ccc-opdr-prd-01-hior
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-prd-01-hior"
      preSteps:
        - script: helm uninstall hior -n ns-ccc-opdr-prd-01-hior || true