trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: hior
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-hior
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-ont-01-hior"
      preSteps:
        - script: helm uninstall hior -n ns-ccc-opdr-ont-01-hior
          displayName: Remove previous installation
        - script: kubectl get secrets
          displayName: kubectl get secrets
