tenantId: 72fca1b1-2c2e-4376-a445-294d80196804  # Global

# Default keyvault for getting secrets
keyVaultName: hior-o-dzvotjkhjpqua  # App specific

# Identity AppID (clientId) used to authenticate with the keyvault
workloadIdentity: a338c40c-c164-48cf-87e7-6dad2c6fd988  # Environment specific

# Service account to use
serviceAccount: app

serviceAccounts:
  app:
    enableWorkloadIdentity: true

# We must select the nodepool to run the pods on
nodepool: cccopdront01  # Environment specific

# Default host for the ingress resources
host: hior.opdr-o.azure.amsterdam.nl  # App specific

# Some default environment variables to inject in all containers
env:
  AZURE_KEY_VAULT: "https://hior-o-dzvotjkhjpqua.vault.azure.net/"  # App specific
  AZURE_MANAGED_IDENTITY_CLIENTID: 03341363-cc33-4976-ae16-27f763f014fd  # Environment specific

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-o-yhqbd6yktpphi  # Environment specific

ingress:
  app:
    className: nginx-internal  # App specific