host: localhost

jobs:
  certificate-init:
    enabled: false

ingress:
  app:
    className: nginx
    tls: null

secrets:
  certificate:
    enabled: false

network:
  allow-ingress:
    enabled: false